### ISSUE TITLE
Fortune grabber fails

### ISSUE THREAD

**Issue by kopiersperre** [ilyavorobiev/fortune-grabber#1]
(env) python2 fortune1000.py
Traceback (most recent call last):
  File "fortune1000.py", line 78, in <module>
    companies = grab()
  File "fortune1000.py", line 36, in grab
    postid = next(attr for attr in soup.body['class'] if attr.startswith('postid'))
  File "/tmp/fortune-grabber/env/lib/python2.7/site-packages/bs4/element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'class'

The URL has changed to http://beta.fortune.com/fortune500/ but this doesn't change the result. May you please investigate the error?

**Comment by iwyatt** [comment]
Same error.

**Comment by roysoumya** [comment]
Mainly the url from which the data was scraped has changed. I have the code and also the csv files in the output folder. I have created a pull request for the same.
